name: Workflow Publisher
on:
 workflow_dispatch:
 push:
   branches: [ 'develop',  'master', 'main' ]
   paths:
   - 'templates/**'
jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [ 'java-service-1' , 'java-service-2' ]
    steps:
      - uses: actions/checkout@v3

      - name: print values
        run: echo ${{ github.repository_owner }}/${{ matrix.target_repo }}

      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          path: ${{ matrix.target_repo }}
          token: ${{ secrets.RW_REPO }}


      - name: Update workflows
        shell: bash
        run: |
          cp ../templates/* ./
        working-directory: ./${{ matrix.target_repo }}


      - name: Publish workflows
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Github Agent | Workflows has updated"
          git push
        working-directory: ./${{ matrix.target_repo }}
